name: Untrusted CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Accept NDK license
        run: echo "y" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager "ndk;29.0.13113456"

      - name: Build
        run: |
          make release -j$(nproc)
          make debug -j$(nproc)

      - name: Upload release
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/NoZygisk-v*-release.zip"
          archive: false

      - name: Upload debug
        uses: actions/upload-artifact@v7
        with:
          path: "build/out/NoZygisk-v*-debug.zip"
          archive: false
